# Generated by Django 2.2.13 on 2021-01-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mode_of_payment',
            field=models.CharField(choices=[('cash', 'cash'), ('paytm', 'paytm'), ('card', 'mastercard'), ('phonepay', 'phonepay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='templates/images'),
        ),
    ]
