# Generated by Django 2.2.13 on 2021-01-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_auto_20210104_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('paid', 'paid')], max_length=20),
        ),
    ]
