# Generated by Django 2.2.13 on 2021-01-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_auto_20210104_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='shoppingCart.Products'),
        ),
    ]
