# Generated by Django 2.2.13 on 2021-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0005_remove_orders_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
