# Generated by Django 2.2.13 on 2021-01-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0008_orders_items_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders_items',
        ),
    ]
