# Generated by Django 2.2.13 on 2021-01-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0010_orders_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_items',
            name='order_id',
        ),
    ]
