# Generated by Django 2.2.13 on 2021-01-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0012_auto_20210105_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_items',
            name='user_id',
        ),
    ]
