# Generated by Django 2.2.13 on 2021-01-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0013_remove_orders_items_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_items',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='shoppingCart.Products'),
        ),
    ]
